---
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Lambda Runtime Tweeter

Parameters:
  Env:
    Type: String
    Default: current

Globals:
  Function:
    AutoPublishAlias: !Ref Env

Resources:
  AlertSNSTopic:
    Type: AWS::SNS::Topic

  DependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/layer

  TweeterFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/tweet
      Handler: index.handler
      Runtime: python3.7
      MemorySize: 512
      Timeout: 150
      Layers:
        - !Ref DependenciesLayer
      Policies:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess
        - Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                - "*"

  TweeterLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${TweeterFunction}
      RetentionInDays: 14