version: 2

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - poetry-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}
      - run:
          name: install and run
          command: |
            set -x

            poetry config virtualenvs.in-project true
            poetry install
            make deploy
      - save_cache:
          paths:
            - .venv
          key: poetry-{{ checksum "pyproject.toml" }}-{{ checksum "poetry.lock" }}

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v([0-9]+\.){2}[0-9]+/