version: 2

jobs:
  deploy:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - run:
          name: install dependencies
          command: |
            set -x

            poetry config --list
      - run:
          name: poetry check
          command: poetry config --list

workflows:
  version: 2
  deploy:
    jobs:
      - deploy
